# Generated by Django 2.2.1 on 2019-05-08 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 12, 12, 33, 334461), verbose_name='published'),
        ),
    ]
