# Generated by Django 2.2.1 on 2019-05-08 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190508_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 13, 13, 8, 560845), verbose_name='published'),
        ),
    ]
